/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/signin': RouteRecordInfo<'/auth/signin', '/auth/signin', Record<never, never>, Record<never, never>>,
    '/bot/': RouteRecordInfo<'/bot/', '/bot', Record<never, never>, Record<never, never>>,
    '/settings/': RouteRecordInfo<'/settings/', '/settings', Record<never, never>, Record<never, never>>,
    '/wildberries/': RouteRecordInfo<'/wildberries/', '/wildberries', Record<never, never>, Record<never, never>>,
    '/wildberries/auth/': RouteRecordInfo<'/wildberries/auth/', '/wildberries/auth', Record<never, never>, Record<never, never>>,
    '/wildberries/supplies/': RouteRecordInfo<'/wildberries/supplies/', '/wildberries/supplies', Record<never, never>, Record<never, never>>,
  }
}
